routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

// Redirect from home to Elon Musk's Tweet Table.
Route::redirect('/', '/elonmusk');

/**
 * This routing group represents what is possible when the time comes to implement the same types of data
 * representations on other social media platforms. With a little more work in the templates to remove the
 * Twitter-specific terminology, these groups could be quickly and easily replicated for any number of other services.
 * Within this group, the `TwitterRepository` acts as the `SocialRepository`. The `TwitterRepository` does the
 * service-specific work of building `SocialPostCollection` and `SocialConnectionCollection` models from the data and
 * structures provided by the Twitter API.
 */
Route::name('twitter.')->group(function () {
    // Bind Twitter as the repository for this group of routes.
    app()->bind(\App\Repositories\SocialRepository::class, \App\Repositories\TwitterRepository::class);

    Route::get('/{handle}', 'SocialPostsController')->name('posts');
    Route::get('/{handle}/followers', 'SocialConnectionsController')->name('connections');
});

resources/views/social/connections.blade.php
@extends('layouts.app')

@section('title', 'Followers of ' . $connections->getUserName())

@section('content')
    <h1 class="page-header">Followers of {{ $connections->getUserName() }} (<a href="{{ $connections->getUserUrl() }}" target="_blank">{{ '@' . $connections->getUserHandle() }}</a>)</h1>
    <p><a href="{{ route('twitter.posts', ['handle' => request('handle')]) }}">Tweets from {{ '@' . $connections->getUserHandle() }}</a></p>
    <p><strong>{{ number_format($connections->getTotal()) }}</strong> total</p>

    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
        <tr>
            <th>Name</th>
            <th>Handle</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($connections as $connection)
            <tr class="
                    @if ($loop->index % 2 == 0)
                        even
                    @else
                        odd
                    @endif

                    @switch($loop->index % 3)
                    @case(0)
                        gradeX
                        @break

                    @case(1)
                        gradeC
                        @break

                    @case(2)
                        gradeA
                        @break
                    @endswitch
                    ">
                <td>{{ $connection->getName() }}</td>
                <td><a href="https://twitter.com/{{ $connection->getHandle() }}" target="_blank">{{ '@' . $connection->getHandle()  }}</a></td>
            </tr>
        @endforeach
        </tbody>
    </table><!-- /.table-responsive -->

    <nav aria-label="Followers navigation">
        <ul class="pagination justify-content-between">
            <li class="page-item"><a class="page-link" href="{{ route('twitter.connections', ['handle' => request('handle'), 'cursor' => $connections->getPrev()]) }}">Previous</a>
            <li class="page-item"><a class="page-link" href="{{ route('twitter.connections', ['handle' => request('handle'), 'cursor' => $connections->getNext()]) }}">Next</a>
        </ul>
    </nav>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#dataTables-example').DataTable({
                info: false,
                ordering: false,
                paging: false,
                responsive: true,
                searching: false,
            });
        });
    </script>
@endsection

resources/views/social/posts.blade.php
@extends('layouts.app')

@section('title', 'Tweets from ' . $posts->getAuthorName())

@section('content')
    <h1 class="page-header">Tweets from {{ $posts->getAuthorName() }} (<a href="{{ $posts->getAuthorUrl() }}" target="_blank">{{ '@' . $posts->getAuthorHandle() }}</a>)</h1>
    <p><a href="{{ route('twitter.connections', ['handle' => request('handle')]) }}">Followers of {{ '@' . $posts->getAuthorHandle() }}</a></p>

    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
        <tr>
            <th>Date</th>
            <th>Tweet</th>
            <th>Likes</th>
            <th>Retweets</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($posts as $post)
            <tr class="
                    @if ($loop->index % 2 == 0)
                        even
                    @else
                        odd
                    @endif

                    @switch($loop->index % 3)
                    @case(0)
                            gradeX
                            @break

                    @case(1)
                            gradeC
                            @break

                    @case(2)
                            gradeA
                            @break
                    @endswitch
                    ">
                <td data-order="{{ $post->getDimensions()->getCreatedAt()->format('U') }}">
                    {{ $post->getDimensions()->getCreatedAt()->format('F jS, Y') }}
                </td>
                <td>{{ $post->getContent()  }}</td>
                <td class="text-right" data-order="{{ $post->getLikes() }}">
                    {{ number_format($post->getLikes()) }}
                </td>
                <td class="text-right" data-order="{{ $post->getShares() }}">
                    {{ number_format($post->getShares()) }}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table><!-- /.table-responsive -->
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#dataTables-example').DataTable({
                order: [[0, 'desc']],
                responsive: true
            });
        });
    </script>
@endsection